name: Deploy Angular to Firebase Hosting

on:
  push:
    branches:
      - render  # O tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install project dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular app
        run: ng build --configuration production

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
